import Header from './components/Header/Haeder'
import './globals.css'
import 'animate.css'
import { ToastNotifications } from './utils/alert'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <ToastNotifications />
        <Header />
        {children}
      </body>
    </html>
  )
}
